version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  datahub:
    build: ./datahub/
    ports:
      - 8000:8000

  data-reporter:
    build: ./data-reporter/

  data-monitor:
    build: ./data-monitor/

volumes:
  mongodb: {}

