version: '3.4'

services:
  mongodb:
    restart: always
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  datahub:
    restart: always
    build: ./datahub/
    ports:
      - 8000:8000
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  data-reporter:
    restart: always
    build: ./data-reporter/
    environment:
      - DATAHUB_BASE_URL=http://datahub:8000

  data-monitor:
    restart: always
    build: ./data-monitor/
    ports:
      - 5000:5000
    environment:
      - MONGO_HOST=mongodb

#  monitoring

  prometheus:
    image: prom/prometheus:v2.7.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  mongodb: {}
  grafana: {}
